#!/bin/sh

# Quick start-stop-daemon example, derived from Debian /etc/init.d/ssh
set -e
case "$1" in
	start)
		echo -n "Starting daemon: "$NAME
#		start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --name $NAME --exec $DAEMON --make-pidfile
		start-stop-daemon -S -n socketserver -a /usr/bin/aesdsocket -- -d
		;;
	stop)
		echo -n "Stopping daemon: "$NAME
#		start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE --remove-pidfile
		start-stop-daemon -K -n socketserver
		;;
	*)
		echo "Usage: "$1" {start|stop}"
		exit 1
esac
